services:
  - type: web
    name: distributed-task-queue
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: bash start.sh
    plan: free
    region: singapore
    envVars:
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_DB_BROKER
        value: "0"
      - key: REDIS_DB_BACKEND
        value: "1"
      - key: API_KEY
        generateValue: true
      - key: APP_ENV
        value: production
